### ISSUE TITLE
Setup compatibiliy question

### ISSUE THREAD

**Issue by mr-gosh** [David00/rpi-power-monitor#1]
I have a digital 2 way Energy counter and in a different room an additional Power Generation counter.

Could this be sanely monitored with your solution?

**Comment by David00** [comment]
Hey there! I also have a 2-way (net) meter from the local utility because I have a grid-tied solar PV system.

So, the project already supports 2-way monitoring and can calculate your total/net imported and exported power. I am not sure what exactly you mean by Power Generation counter, but maybe referencing the diagram of my system in the project Wiki will help:
![](
![image](https://user-images.githubusercontent.com/17997328/85951638-415a9d80-b919-11ea-9ab4-4f338fe64a42.png)


See how my solar inverter is fed into my main panel? This means that if I am producing power back into the grid, CT #0 will be _negative_, but if I am importing power from the grid, CT #0 will be positive.

Here is the section in the code where the whole-home power is calculated.
https://github.com/David00/rpi-power-monitor/blob/master/power-monitor.py#L483

If you have a source of power production, you'll most likely need to modify the section linked above to properly account for your overall net usage.
