### ISSUE TITLE
Home Assistant Integration

### ISSUE THREAD

**Issue by misterjtc** [David00/rpi-power-monitor#113]
I see that in the docs there is a todo for homeasssitant integration. I am curious if there is a rough timeline for this?

Homeassitant has an energy tab out of the box and it would be pretty slick to be able to push the data from the power monitor to there.

**Comment by David00** [comment]
There have been a couple of contributions regarding Home Assistant, which I think is fantastic!  There is a discussion thread about Home Assistant, which looks like it could use an update with the recent additions related to this.  I'll go ahead and update the discussion, and close this issue so that we can keep all the conversation in one place :)

## [Home Assistant Integrations](https://github.com/David00/rpi-power-monitor/discussions/70)
