### ISSUE TITLE
Current spike suppression?

### ISSUE THREAD

**Issue by altontoth** [David00/rpi-power-monitor#34]
![Capture](https://user-images.githubusercontent.com/52620797/120717296-27f09880-c47c-11eb-961d-db4e1c1e98be.JPG)

Not so much as an issue specifically, as much as it is seeing if anyone has a clever method for eliminating spikes, either through software or hardware changes? I have a panel that I'm monitoring which includes a well pump, and every time the well pump kicks on, you can see spikes in all of the channels due to induction. CT2 is monitoring one leg of the pump circuit (240V pump). CT4 and CT5 are monitoring my mains, so I would expect to see a spike there, but the others (0, 1, 3) have nothing to do with the pump. Thoughts? I was thinking of using shielded wire, but I'm having a hard time finding it. I'm also considering buying a series of chokes. But I'm wondering if there's anything to do for it in software?

**Comment by David00** [comment]
Wow, that's a neat capture - thanks for sharing!  How are your CT leads ran, and are each pair of CT leads twisted together?
A choke probably won't do very much good for this since they aim to reduce the impact from a specific frequency. This is likely capacitive cross talk from the conductor that is supplying the current to the pump motor.

Shielded wire might be your best bet - just pick up a shielded cat5e cable and cut one of the ends off, and attach your CT leads to the cutoff end. More details about using cat5e are [here](https://github.com/David00/rpi-power-monitor/wiki/Hardware-Assembly#assembling-the-current-transformer-cat5e-cable) in the Wiki. The PCB's RJ45 jack accepts a shielded cat5e cable (with the proper shielded RJ45 connector) and will ground the cable's shield to the PCB, which should help reduce this type of noise.

It's also a good idea to keep the CT leads as far away from the current-carrying conductors in your electrical system. And try to **avoid** running the CT leads close to and parallel with the current-carrying conductors.

For software, you could try increasing Grafana's `GROUP BY` parameter to `30s` or more. This will essentially just average the data out and help flatten the appearance of the data when graphed.
