### ISSUE TITLE
Current measuring will not read zero

### ISSUE THREAD

**Issue by chenhoulin6204** [David00/rpi-power-monitor#37]
So, I've done everything in the wiki, only difference is my board is completed on a bread board instead of a PCB.

Now, when I'm running the power monitor in terminal mode, I see there is always a current reading of about .5 Amps even when the CTs are not connected, in fact even if I ground CT_input to GND, there is still a .5 Amps reading. When there is actually load, the current measurement is roughly accurate.

This 0.5A messes with the power consumption calculation, because this means there will be a 100W consumption even when nothing is connected, and that's unacceptable. I don't know what is the problem, the ADC, the capacitors I used, the OpAmp, I do not know, please advise!
![image](https://user-images.githubusercontent.com/55968144/133992476-431f2713-4807-487d-913d-d202f57397f5.png)

**Comment by David00** [comment]
The breadboard is most likely the culprit here. Breadboards and jumper wires are prone to noise like crazy. It could also be that your sample rate is very low.  

The values for current that you're seeing are simply the RMS values as calculated based off the raw sample data. So, if the values are wrong, something is wrong with your raw data.

You can plot the raw data and check the sample rate using [debug mode](https://github.com/David00/rpi-power-monitor/wiki/Software-1.-Overview#debug-mode).
