### ISSUE TITLE
Enhancement: export data to MQTT

### ISSUE THREAD

**Issue by richie256** [David00/rpi-power-monitor#38]
I was wondering if anyone would be interested about exporting crunched data into MQTT to be able integrate it into Home Assistant Energy consumption? I think that would be a nice feature to add.

**Comment by emersonsc** [comment]
Any thoughts on implementation of this "fix" so it's just part of the software?

**Comment by David00** [comment]
I'd like to explore this - my only hesitation is that I personally am not familiar with Home Assistant or other MQTT systems, so if I bring MQTT functionality into the project, I now have at least some responsibility to support it.  So, I just need to get familiar with HA and MQTT.

**Comment by emersonsc** [comment]
> I'd like to explore this - my only hesitation is that I personally am not familiar with Home Assistant or other MQTT systems, so if I bring MQTT functionality into the project, I now have at least some responsibility to support it. So, I just need to get familiar with HA and MQTT.

I think it would be an excellent idea. I think with the MQTT functionality which would make it HA friendly this project would get some great exposure!

I clicked the link you supplied in this thread but I'm not sure how to actually use the code he provided. There isn't much for explanation or instructions on how to implement it after the dependencies are installed.

**Comment by shingle01** [comment]
I just wanted to second the notion that it'd be nice for powermon to export to mqtt natively.

I'm testing 0.3.0 and using heytensai's script to export to mqtt.  The script is perfect for updating Home Assistant every minute.

But I'm looking for a more real-time solution.  Powermon seems to be sending raw ct values to influxdb every 5sec.  Given powerson is taking 1000 samples per second it feels like a missed opportunity not to be able to export raw values to mqtt every second, bypassing influxdb.

**Comment by emersonsc** [comment]
> I just wanted to second the notion that it'd be nice for powermon to export to mqtt natively.
> 
> I'm testing 0.3.0 and using heytensai's script to export to mqtt. The script is perfect for updating Home Assistant every minute.
> 
> But I'm looking for a more real-time solution. Powermon seems to be sending raw ct values to influxdb every 5sec. Given powerson is taking 1000 samples per second it feels like a missed opportunity not to be able to export raw values to mqtt every second, bypassing influxdb.

To be honest I set up a merge request to pull have the option to have the power monitor send the data to influxdb on the HA server and then create sensors from there. I found it works out much better than using mqtt.

**Comment by David00** [comment]
> I just wanted to second the notion that it'd be nice for powermon to export to mqtt natively.

I agree! I do intend to support MQTT, and I've even [started a section in the docs](https://david00.github.io/rpi-power-monitor/docs/v0.3.0/advanced-usage.html#integrations-home-assistant-etc) for various integrations (like MQTT).

> To be honest I set up a merge request to pull have the option to have the power monitor send the data to influxdb on the HA server and then create sensors from there. I found it works out much better than using mqtt.

@emersonsc Thank you again for the PR. Now that v0.3.0 is out, I will get back to reviewing it. Quite a bit has changed with the new config file method so I suspect some changes will be needed to your PR, which I'm happy to do.

I personally don't use HA, so I will need to setup an HA server and play around with it to see what it's all about. I'm also not that familiar with MQTT, but it does seem to be popular alongside HA based on the inquiries I receive.

**Comment by emersonsc** [comment]
> > I just wanted to second the notion that it'd be nice for powermon to export to mqtt natively.
> 
> I agree! I do intend to support MQTT, and I've even [started a section in the docs](https://david00.github.io/rpi-power-monitor/docs/v0.3.0/advanced-usage.html#integrations-home-assistant-etc) for various integrations (like MQTT).
> 
> > To be honest I set up a merge request to pull have the option to have the power monitor send the data to influxdb on the HA server and then create sensors from there. I found it works out much better than using mqtt.
> 
> @emersonsc Thank you again for the PR. Now that v0.3.0 is out, I will get back to reviewing it. Quite a bit has changed with the new config file method so I suspect some changes will be needed to your PR, which I'm happy to do.
> 
> I personally don't use HA, so I will need to setup an HA server and play around with it to see what it's all about. I'm also not that familiar with MQTT, but it does seem to be popular alongside HA based on the inquiries I receive.

Ah, I've been so busy with the high school robotics stuff I have been out of the loop with all my projects! I'll have to work on upgrading mine to v0.3.0 and document the process. Just quickly glancing through your new docs it looks like the set up on the PM side will be simpler, and the HA side won't really change.

**Comment by David00** [comment]
> I just wanted to second the notion that it'd be nice for powermon to export to mqtt natively.
> 
> I'm testing 0.3.0 and using heytensai's script to export to mqtt. The script is perfect for updating Home Assistant every minute.
> 
> But I'm looking for a more real-time solution. Powermon seems to be sending raw ct values to influxdb every 5sec. Given powerson is taking 1000 samples per second it feels like a missed opportunity not to be able to export raw values to mqtt every second, bypassing influxdb.
> 
> EDIT: powermon is exporting to influxdb almost every second. I have noticed there can be a lag period when influx updates. So if you're querying influx for the mean power for the past 2 seconds you will likely get an empty result.
> 
> `influx -database power_monitor -execute "select mean(power) from raw_cts WHERE ct= '${ct}' AND time >= now() - 10s GROUP BY time(2) ORDER BY time DESC"` ![image](https://user-images.githubusercontent.com/43157345/231052575-da8ba7c6-fcb0-44f7-9a88-87596cd6447a.png)


@shingle01 - I see your edit, and the reason for the apparent lag is that several individual measurements are batched together before being sent to InfluxDB for storage. The timestamps of each measurement stay associated to each respective measurement which is why it appears to lag,  The reason for doing this is that there is some overhead in writing data to InfluxDB, so writing more data in a single transaction reduces the total overhead.

If you're curious, the specific part of the code that handles this is here:

https://github.com/David00/rpi-power-monitor/blob/defaa2a233161ac02f929f9866c0a88e20e09843/rpi_power_monitor/power_monitor.py#L927-L937

25 points is an arbitrary number I selected to keep the power monitor "responsive", but it's actually recommended to be much higher with [5000 points per batch](https://docs.influxdata.com/influxdb/v2.0/write-data/best-practices/optimize-writes/#batch-writes) (at least for Influx v2.0 - not sure about 1.8).

Another factor that plays into the update rate is the number of raw samples that are collected for the power calculation, which is set here:

https://github.com/David00/rpi-power-monitor/blob/defaa2a233161ac02f929f9866c0a88e20e09843/rpi_power_monitor/power_monitor.py#L765

This is the number of samples that are taken from each _enabled_ channel, and these samples are then fed to the power calculation function.  The per-channel sample rate is usually about 3300 samples per second, so even with 1000 samples, you're still looking at less than half a second's worth of power usage.

Finally, another factor that impacts the overall update rate is the number of channels you've enabled in `config.toml`. By default, all channels are enabled.  If you disable a channel, it is no longer sampled, which means the per-channel sample rate is increased, and the sampling, calculation, and storage operations will appear to run faster.

---

@shingle01, it looks like you can accomplish what you're trying to do with @emersonsc's HA integration notes, perhaps paired with a reduction (or complete elimination) of the `batch_size` that I've linked above.  

@emersonsc's README is located here and the general process still looks to be accurate, with only a few small changes needed to reference the new `config.toml` (instead of `config.py`):

https://github.com/David00/rpi-power-monitor/blob/38cbd9959e0fb208bd5e38b950ebc931c72a6d60/Home%20Assistant/Readme.md

Also, this brings up the idea of exposing some of these internal configuration values to the end user, since editing the code of a git-linked project makes future updates/merges tricky.  I am open to the idea of updating the existing configuration file to expose the settings mentioned above to allow you to easily tweak some of the internal stuff that impacts the update rates.

**Comment by corbolais** [comment]
> I'd like to explore this - my only hesitation is that I personally am not familiar with Home Assistant or other MQTT systems, so if I bring MQTT functionality into the project, I now have at least some responsibility to support it. So, I just need to get familiar with HA and MQTT.

Most implementations leverage the trinity MQTT <- Telegraf -> Influx. The MQTT part is usually done by mosquitto.

Telegraf subscribes to topics with the MQTT broker and pushes the received MQTT msgs to influx, possibly mangling them on the way. I.e. switching events like ON/OFF can be mangled to be 0/1 events which then get pushed into influx.

Cheers
