### ISSUE TITLE
Potential of using PI PoE HAT

### ISSUE THREAD

**Issue by JTT-JustTheTip** [David00/rpi-power-monitor#6]
Is there the potential of using a PoE HAT with the GPIO pin headers passed through to the monitor board. This way you only need a single cable run to the meter cupboard.

**Comment by David00** [comment]
Hey there,  I would say there is potential to use a PoE hat, but I'm unavailable to test. I have the NavoLabs.com Pi 3B+ PoE hat, but my 3B+ is currently in use.  The good news is that the NavoLabs supplies power over the 5V rail and this project uses the 3.3V rail, so any potential noise coming in over the PoE supply should be at least somewhat separated.  The power utilization of the custom hat is negligible at less than 1mA. 

Your Pi would need an extra tall "stacking" header so that the headers can extend through the PoE hat and support my power monitoring hat. You'd also need some extra long standoffs.  If you're able to test with a PoE hat, I would really like to hear how it goes. You can run the software in [debug mode](https://github.com/David00/rpi-power-monitor/wiki/Software-1.-Post-Installation-Setup#debug-mode) to generate a plot and inspect the harmonics of each input for the noise level. 

Also, this project requires a 9V AC input source, so you'll still need a nearby outlet to plug in a 9V AC to AC transformer and connect it to the power monitor hat. So, using PoE may not be worth the effort.
